/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "App.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Descriptor bindings are rebuilt from the hand-maintained App.pb.h schema. */
PB_BIND(VersionMsg, VersionMsg, AUTO)


PB_BIND(InfoFieldMsg, InfoFieldMsg, AUTO)


PB_BIND(InfoBlockMsg, InfoBlockMsg, AUTO)


PB_BIND(AppMsg, AppMsg, AUTO)
